{% set version = '2.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mongotools
  version: {{ version|replace("-", "_") }}

source:
  path: ..

build:
  merge_build_host: True  # [win32 or win64]
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, mongolitedt
requirements:
  build:

  host:
    - r-base >=4.0.3
    - r-dplyr >=1.0.0
    - r-jsonlite
    - r-lubridate
    - r-mongolite >=2.2

  run:
    - r-base >=4.0.3
    - r-dplyr >=1.0.0
    - r-jsonlite
    - r-lubridate
    - r-mongolite >=2.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mongoTools')"           # [not win]
    - "\"%R%\" -e \"library('mongoTools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mongoTools
  license: Private
  summary: A set of tools to assist the user requesting data from mongoDB. We cover in particular
    query generating and cluster connection. The package is meant to complete mongolite.
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: mongoTools
# Title: Functions to Interact with MongoDB
# Version: 1.3.2
# Authors@R: person("Tarak", "Kharrat", email = "tarak.kharrat@gmail.com", role = c("aut", "cre"))
# Description: A set of tools to assist the user requesting data from mongoDB. We cover in particular query generating and cluster connection. The package is meant to complete mongolite.
# Depends: R (>= 3.3.0), mongolite (>= 2.0)
# Imports: dplyr, jsonlite, lubridate
# Suggests: testthat, mongolitedt
# License: Private
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 5.0.1
# Collate: 'MongoTools.R' 'query.R' 'urls.R' 'replicate.R' 'saveObject.R' 'stats.R' 'tools.R' 'wrapper.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2019-02-24 14:20:25 UTC; ISDADS\aqs566
# Author: Tarak Kharrat [aut, cre]
# Maintainer: Tarak Kharrat <tarak.kharrat@gmail.com>

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
